### ISSUE TITLE
Crash during initialisation of security providers

### ISSUE THREAD

**Issue by dasisdormax** [dkimitsa/robovm-libcore10-smoketest#3]
Yesterday I began to test our LibGDX based game with the libcore10 based robovm. I created a fork and built from source, with robovm master and libcore10 merged.

After switching to the conservative tree shaker, the game did launch. However, it crashed on calls to `java.security.MessageDigest.getInstance("SHA-1")` and `new java.security.SecureRandom()` with an AssertionError("Unable to configure default providers") in sun.security.jca.Providers.

For my game, I 'fixed' it by disabling that check and adding `<pattern>com.android.org.conscrypt.**</pattern>` to forceLinkClasses in robovm.xml. I assume however, a better fix would be necessary for a release version.

If you can use any more information or work from my side, I would be happy to help.

I did not notice any other issues in my game. Thanks for your work!

**Comment by dkimitsa** [comment]
thanks for feedback. it is abandoned for a while by I plan to be back there on it in week or two

**Comment by dkimitsa** [comment]
@dasisdormax 
hi, this was fixed in [build #3 ](https://github.com/robovmx/robovmx/releases/tag/x2-libcore12-v10.2.2-20220819), closing. please open a new issue if any at [robovmx](https://github.com/robovmx/robovmx/issues) issue page
