### ISSUE TITLE
It cannot import the plugin

### ISSUE THREAD

**Issue by congcoi123** [dkimitsa/robovm-libcore10-smoketest#4]
Hi @dkimitsa, Thanks so much for your time working on this awesome project. I tried to import the plugin into both IntelliJ and Android Studio but it seems there is an issue.
Attached you can find the screenshot.
Could you please spare some time to take a look?
I appreciate your support.
<img width="976" alt="Screenshot 2023-03-19 at 11 52 41" src="https://user-images.githubusercontent.com/4993410/226171314-f075b7fc-5ce8-420f-b367-2bfb8990faaf.png">

**Comment by dkimitsa** [comment]
hi, 
try installing last available build from https://github.com/robovmx/robovmx/releases/tag/x2-libcore12-v10.2.2-20220819
don't unpack zip file of plugin
